import SWELib.Networking.Http
import SWELib.Networking.Http.Target
import SWELib.Networking.Proxy.Http
import SWELib.Basics.Uri

/-!
# HTTP Conformance Tests

Executable #eval tests verifying the HTTP formalization matches RFC 9110.
Generated by conformance testing agent.
-/

namespace HttpConformanceTest

open SWELib.Networking.Http
open SWELib.Basics

-- Section 1: Method Properties Tests
section MethodTests

-- Test 1.1: Safe methods are GET, HEAD, OPTIONS, TRACE
#eval decide (Method.GET.isSafe = true)
#eval decide (Method.HEAD.isSafe = true)
#eval decide (Method.OPTIONS.isSafe = true)
#eval decide (Method.TRACE.isSafe = true)
#eval decide (Method.POST.isSafe = false)
#eval decide (Method.PUT.isSafe = false)
#eval decide (Method.DELETE.isSafe = false)
#eval decide (Method.CONNECT.isSafe = false)

-- Test 1.2: Idempotent methods are GET, HEAD, PUT, DELETE, OPTIONS, TRACE
#eval decide (Method.GET.isIdempotent = true)
#eval decide (Method.HEAD.isIdempotent = true)
#eval decide (Method.PUT.isIdempotent = true)
#eval decide (Method.DELETE.isIdempotent = true)
#eval decide (Method.OPTIONS.isIdempotent = true)
#eval decide (Method.TRACE.isIdempotent = true)
#eval decide (Method.POST.isIdempotent = false)
#eval decide (Method.CONNECT.isIdempotent = false)

-- Test 1.3: Cacheable by default: only GET and HEAD
#eval decide (Method.GET.isCacheableByDefault = true)
#eval decide (Method.HEAD.isCacheableByDefault = true)
#eval decide (Method.POST.isCacheableByDefault = false)
#eval decide (Method.PUT.isCacheableByDefault = false)
#eval decide (Method.DELETE.isCacheableByDefault = false)
#eval decide (Method.CONNECT.isCacheableByDefault = false)
#eval decide (Method.OPTIONS.isCacheableByDefault = false)
#eval decide (Method.TRACE.isCacheableByDefault = false)

-- Test 1.4: Theorem: safe_implies_idempotent
-- Verify for each safe method that it is also idempotent
#eval decide (Method.GET.isSafe → Method.GET.isIdempotent)
#eval decide (Method.HEAD.isSafe → Method.HEAD.isIdempotent)
#eval decide (Method.OPTIONS.isSafe → Method.OPTIONS.isIdempotent)
#eval decide (Method.TRACE.isSafe → Method.TRACE.isIdempotent)

-- Test 1.5: Theorem: cacheableByDefault_implies_safe
-- Verify for each cacheable-by-default method that it is safe
#eval decide (Method.GET.isCacheableByDefault → Method.GET.isSafe)
#eval decide (Method.HEAD.isCacheableByDefault → Method.HEAD.isSafe)

-- Test 1.6: Request body expected
#eval decide (Method.POST.requestBodyExpected = true)
#eval decide (Method.PUT.requestBodyExpected = true)
#eval decide (Method.GET.requestBodyExpected = false)
#eval decide (Method.HEAD.requestBodyExpected = false)
#eval decide (Method.DELETE.requestBodyExpected = false)
#eval decide (Method.OPTIONS.requestBodyExpected = false)
#eval decide (Method.TRACE.requestBodyExpected = false)

-- Test 1.7: Extension methods
def customMethod : Method := Method.extension "PATCH"
#eval repr customMethod
#eval decide (customMethod.isSafe = false)
#eval decide (customMethod.isIdempotent = false)
#eval decide (customMethod.isCacheableByDefault = false)

-- Test 1.8: Method string representation
#eval toString Method.GET
#eval toString Method.POST
#eval toString (Method.extension "CUSTOM")

end MethodTests

-- Section 2: Status Code Tests
section StatusCodeTests

-- Test 2.1: Valid range 100-999
def validStatus100 : StatusCode := ⟨100, by decide⟩
def validStatus999 : StatusCode := ⟨999, by decide⟩
#eval repr validStatus100
#eval repr validStatus999

-- Test 2.2: Status classes
#eval decide (StatusCode.continue_.statusClass = some StatusClass.informational)
#eval decide (StatusCode.ok.statusClass = some StatusClass.successful)
#eval decide (StatusCode.movedPermanently.statusClass = some StatusClass.redirection)
#eval decide (StatusCode.badRequest.statusClass = some StatusClass.clientError)
#eval decide (StatusCode.internalServerError.statusClass = some StatusClass.serverError)

-- Test 2.3: Body constraints - 1xx, 204, 304 MUST NOT have body
#eval decide (StatusCode.continue_.mayHaveBody = false)
#eval decide (StatusCode.switchingProtocols.mayHaveBody = false)
#eval decide (StatusCode.noContent.mayHaveBody = false)
#eval decide (StatusCode.notModified.mayHaveBody = false)
#eval decide (StatusCode.ok.mayHaveBody = true)
#eval decide (StatusCode.created.mayHaveBody = true)

-- Test 2.4: Interim vs Final status
#eval decide (StatusCode.continue_.isInterim = true)
#eval decide (StatusCode.continue_.isFinal = false)
#eval decide (StatusCode.ok.isInterim = false)
#eval decide (StatusCode.ok.isFinal = true)

-- Test 2.5: Error status codes
#eval decide (StatusCode.badRequest.isError = true)
#eval decide (StatusCode.internalServerError.isError = true)
#eval decide (StatusCode.ok.isError = false)
#eval decide (StatusCode.movedPermanently.isError = false)

-- Test 2.6: Theorem: interim_no_body
-- All interim (1xx) responses should not have body
#eval decide (StatusCode.continue_.isInterim → ¬StatusCode.continue_.mayHaveBody)
#eval decide (StatusCode.switchingProtocols.isInterim → ¬StatusCode.switchingProtocols.mayHaveBody)

-- Test 2.7: Theorem: error_is_final
-- All error status codes are final responses
#eval decide (StatusCode.badRequest.isError → StatusCode.badRequest.isFinal)
#eval decide (StatusCode.internalServerError.isError → StatusCode.internalServerError.isFinal)

-- Test 2.8: Well-known status codes
#eval decide (StatusCode.ok.code = 200)
#eval decide (StatusCode.noContent.code = 204)
#eval decide (StatusCode.notModified.code = 304)
#eval decide (StatusCode.badRequest.code = 400)
#eval decide (StatusCode.notFound.code = 404)
#eval decide (StatusCode.methodNotAllowed.code = 405)
#eval decide (StatusCode.internalServerError.code = 500)

end StatusCodeTests

-- Section 3: Header Field Tests
section FieldTests

-- Test 3.1: Case-insensitive field name comparison
def hostLower : FieldName := ⟨"host"⟩
def hostUpper : FieldName := ⟨"HOST"⟩
def hostMixed : FieldName := ⟨"Host"⟩
#eval decide (hostLower == hostUpper)
#eval decide (hostUpper == hostMixed)
#eval decide (hostLower == hostMixed)

-- Test 3.2: Header list operations
def testHeaders : Headers := [
  { name := FieldName.host, value := "example.com" },
  { name := FieldName.contentType, value := "text/html" },
  { name := FieldName.accept, value := "text/html" },
  { name := FieldName.accept, value := "application/json" }
]

-- Test 3.3: get? - get first value
#eval testHeaders.get? FieldName.host
#eval testHeaders.get? FieldName.contentType
#eval testHeaders.get? FieldName.accept
#eval testHeaders.get? FieldName.contentLength

-- Test 3.4: getAll - get all values for a field
#eval testHeaders.getAll FieldName.accept
#eval testHeaders.getAll FieldName.host
#eval testHeaders.getAll FieldName.contentLength

-- Test 3.5: getCombined - combine all values with ", "
#eval testHeaders.getCombined FieldName.accept
#eval testHeaders.getCombined FieldName.host
#eval testHeaders.getCombined FieldName.contentLength

-- Test 3.6: contains - check if field exists
#eval decide (testHeaders.contains FieldName.host)
#eval decide (testHeaders.contains FieldName.accept)
#eval decide (testHeaders.contains FieldName.contentLength)

-- Test 3.7: add - add a field
def updatedHeaders := testHeaders.add FieldName.contentLength "42"
#eval updatedHeaders.get? FieldName.contentLength

-- Test 3.8: remove - remove all fields with name
def removedHeaders := testHeaders.remove FieldName.accept
#eval decide (removedHeaders.contains FieldName.accept = false)
#eval decide (removedHeaders.contains FieldName.host = true)

-- Test 3.9: Content-Length parsing
def headersWithContentLength : Headers := [
  { name := FieldName.contentLength, value := "123" }
]
def headersWithInvalidContentLength : Headers := [
  { name := FieldName.contentLength, value := "not-a-number" }
]
#eval headersWithContentLength.getContentLength
#eval headersWithInvalidContentLength.getContentLength

-- Test 3.10: Theorem: getAll_nil
#eval Headers.getAll [] FieldName.host

-- Test 3.11: Well-known field names
#eval repr FieldName.host
#eval repr FieldName.contentType
#eval repr FieldName.contentLength
#eval repr FieldName.etag
#eval repr FieldName.allow

end FieldTests

-- Section 4: Request Target Tests
section TargetTests

-- Test 4.1: Default ports for schemes
#eval SWELib.Networking.Http.defaultPort "http"
#eval SWELib.Networking.Http.defaultPort "https"
#eval SWELib.Networking.Http.defaultPort "ftp"

-- Test 4.2: Effective port resolution
def httpUri : Uri := {
  scheme := "http"
  authority := some { host := "example.com", port := none }
}
def httpsUri : Uri := {
  scheme := "https"
  authority := some { host := "example.com", port := none }
}
def httpUriWithPort : Uri := {
  scheme := "http"
  authority := some { host := "example.com", port := some 8080 }
}
-- Note: effectivePort is defined in Http.Target, not Uri
#eval SWELib.Networking.Http.Uri.effectivePort httpUri
#eval SWELib.Networking.Http.Uri.effectivePort httpsUri
#eval SWELib.Networking.Http.Uri.effectivePort httpUriWithPort

-- Test 4.3: Non-empty host validation
def uriWithHost : Uri := {
  scheme := "http"
  authority := some { host := "example.com", port := none }
}
def uriWithEmptyHost : Uri := {
  scheme := "http"
  authority := some { host := "", port := none }
}
def uriNoAuthority : Uri := {
  scheme := "http"
  authority := none
}
-- Note: hasNonEmptyHost is defined in Http.Target, not Uri
#eval decide (SWELib.Networking.Http.Uri.hasNonEmptyHost uriWithHost = true)
#eval decide (SWELib.Networking.Http.Uri.hasNonEmptyHost uriWithEmptyHost = false)
#eval decide (SWELib.Networking.Http.Uri.hasNonEmptyHost uriNoAuthority = false)

-- Test 4.4: Request target forms
def originFormTarget := RequestTarget.originForm "/path/to/resource" (some "q=test")
def absoluteFormTarget := RequestTarget.absoluteForm httpUri
def authorityFormTarget := RequestTarget.authorityForm "example.com" 443
def asteriskFormTarget := RequestTarget.asteriskForm
#eval repr originFormTarget
#eval repr absoluteFormTarget
#eval repr authorityFormTarget
#eval repr asteriskFormTarget

-- Test 4.5: Theorem: defaultPort_http
#eval decide (SWELib.Networking.Http.defaultPort "http" = some 80)

-- Test 4.6: Theorem: defaultPort_https
#eval decide (SWELib.Networking.Http.defaultPort "https" = some 443)

end TargetTests

-- Section 5: ETag Operations Tests
section ETagTests

-- Test 5.1: Strong vs weak ETags
def strongETag1 : ETag := { value := "abc123", weak := false }
def strongETag2 : ETag := { value := "abc123", weak := false }
def strongETag3 : ETag := { value := "def456", weak := false }
def weakETag1 : ETag := { value := "abc123", weak := true }
def weakETag2 : ETag := { value := "abc123", weak := true }

-- Test 5.2: Strong comparison
#eval decide (strongETag1.strongEq strongETag2 = true)
#eval decide (strongETag1.strongEq strongETag3 = false)
#eval decide (strongETag1.strongEq weakETag1 = false)
#eval decide (weakETag1.strongEq weakETag2 = false)

-- Test 5.3: Weak comparison
#eval decide (strongETag1.weakEq strongETag2 = true)
#eval decide (strongETag1.weakEq weakETag1 = true)
#eval decide (weakETag1.weakEq weakETag2 = true)
#eval decide (strongETag1.weakEq strongETag3 = false)

-- Test 5.4: Theorem: strong_implies_weak
#eval decide (strongETag1.strongEq strongETag2 → strongETag1.weakEq strongETag2)

-- Test 5.5: Theorem: weakEq_refl (reflexivity)
#eval decide (strongETag1.weakEq strongETag1 = true)
#eval decide (weakETag1.weakEq weakETag1 = true)

-- Test 5.6: Theorem: weakEq_symm (symmetry)
#eval decide ((strongETag1.weakEq weakETag1) = (weakETag1.weakEq strongETag1))

-- Test 5.7: String representation
#eval toString strongETag1
#eval toString weakETag1

end ETagTests

-- Section 6: Message Structure Tests
section MessageTests

-- Test 6.1: HTTP Version
#eval repr Version.http10
#eval repr Version.http11
#eval repr Version.http2
#eval repr Version.http3
#eval toString Version.http11

-- Test 6.2: Request construction
def testRequest : Request := {
  method := Method.GET
  target := RequestTarget.originForm "/test" none
  headers := [{ name := FieldName.host, value := "example.com" }]
  body := none
  version := Version.http11
}
-- Cannot repr Request without instance, test fields instead
#eval testRequest.host
#eval testRequest.contentLength

-- Test 6.3: Response construction
def testResponse : Response := {
  status := StatusCode.ok
  headers := [
    { name := FieldName.contentType, value := "text/plain" },
    { name := FieldName.contentLength, value := "13" }
  ]
  body := some "Hello, World!".toUTF8
  version := Version.http11
}
-- Cannot repr Response without instance, test fields instead
#eval testResponse.contentType
#eval testResponse.contentLength

-- Test 6.4: Redirect detection
def redirectResponse : Response := {
  status := StatusCode.movedPermanently
  headers := [{ name := FieldName.location, value := "https://example.com/new" }]
}
def nonRedirectResponse : Response := {
  status := StatusCode.ok
  headers := [{ name := FieldName.contentType, value := "text/html" }]
}
#eval decide (redirectResponse.isRedirect = true)
#eval decide (nonRedirectResponse.isRedirect = false)

end MessageTests

-- Section 7: Media Type Tests
section MediaTypeTests

-- Test 7.1: Media type equality (case-insensitive)
def textHtml1 : MediaType := ⟨"text", "html", []⟩
def textHtml2 : MediaType := ⟨"TEXT", "HTML", []⟩
def textHtml3 : MediaType := ⟨"Text", "Html", [("charset", "utf-8")]⟩
def textPlain : MediaType := ⟨"text", "plain", []⟩

#eval decide (textHtml1 == textHtml2)
#eval decide (textHtml1 == textHtml3) -- Parameters don't affect equality
#eval decide (textHtml1 == textPlain)

-- Test 7.2: String representation
#eval toString MediaType.textPlain
#eval toString MediaType.applicationJson
#eval toString { type_ := "text", subtype := "html", parameters := [("charset", "utf-8")] : MediaType }

-- Test 7.3: Common media types
#eval repr MediaType.textPlain
#eval repr MediaType.textHtml
#eval repr MediaType.applicationJson
#eval repr MediaType.applicationOctetStream
#eval repr MediaType.multipartFormData

end MediaTypeTests

-- Section 8: Contract Validation Tests
section ContractTests

-- Test 8.1: Request validity - Host header
def requestWithHost : Request := {
  method := Method.GET
  target := RequestTarget.originForm "/" none
  headers := [{ name := FieldName.host, value := "example.com" }]
}
def requestNoHost : Request := {
  method := Method.GET
  target := RequestTarget.originForm "/" none
  headers := []
}
#eval decide (requestWithHost.hasHost = true)
#eval decide (requestNoHost.hasHost = false)

-- Test 8.2: Request validity - TRACE no body
-- These tests verify the contract properties but can't directly test Props
-- We test the conditions that would make the Props true/false
def traceRequest : Request := {
  method := Method.TRACE
  target := RequestTarget.originForm "/" none
  body := none
}
def traceWithBody : Request := {
  method := Method.TRACE
  target := RequestTarget.originForm "/" none
  body := some ⟨#[1, 2, 3]⟩
}
#eval decide (traceRequest.method = Method.TRACE ∧ traceRequest.body = none)
#eval decide (traceWithBody.method = Method.TRACE ∧ traceWithBody.body ≠ none)

-- Test 8.3: Request validity - asterisk form only with OPTIONS
def optionsAsterisk : Request := {
  method := Method.OPTIONS
  target := RequestTarget.asteriskForm
}
def getAsterisk : Request := {
  method := Method.GET
  target := RequestTarget.asteriskForm
}
-- Testing individual conditions since RequestTarget lacks Decidable instance
#eval decide (match optionsAsterisk.target with
  | RequestTarget.asteriskForm => optionsAsterisk.method = Method.OPTIONS
  | _ => false)
#eval decide (match getAsterisk.target with
  | RequestTarget.asteriskForm => getAsterisk.method ≠ Method.OPTIONS
  | _ => false)

-- Test 8.4: Request validity - authority form only with CONNECT
def connectAuthority : Request := {
  method := Method.CONNECT
  target := RequestTarget.authorityForm "example.com" 443
}
#eval decide (connectAuthority.method = Method.CONNECT)
#eval match connectAuthority.target with
  | RequestTarget.authorityForm _ _ => true
  | _ => false

-- Test 8.5: Response validity - 1xx, 204, 304 no body
def response100 : Response := { status := StatusCode.continue_, body := none }
def response204 : Response := { status := StatusCode.noContent, body := none }
def response304 : Response := { status := StatusCode.notModified, body := none }
def response200 : Response := { status := StatusCode.ok, body := some ⟨#[]⟩ }

#eval decide (response100.status.mayHaveBody = false)
#eval decide (response204.status.mayHaveBody = false)
#eval decide (response304.status.mayHaveBody = false)
#eval decide (response200.status.mayHaveBody = true)

-- Test 8.6: Response validity - 405 must have Allow header
def response405WithAllow : Response := {
  status := StatusCode.methodNotAllowed
  headers := [{ name := FieldName.allow, value := "GET, HEAD, POST" }]
}
def response405NoAllow : Response := {
  status := StatusCode.methodNotAllowed
  headers := []
}
#eval decide (response405WithAllow.status.code = 405 ∧ response405WithAllow.headers.contains FieldName.allow)
#eval decide (response405NoAllow.status.code = 405 ∧ ¬response405NoAllow.headers.contains FieldName.allow)

-- Test 8.7: Content-Length validity
def responseWithValidLength : Response := {
  status := StatusCode.ok
  headers := [{ name := FieldName.contentLength, value := "5" }]
  body := some ⟨#[72, 101, 108, 108, 111]⟩  -- "Hello"
}
def responseWithInvalidLength : Response := {
  status := StatusCode.ok
  headers := [{ name := FieldName.contentLength, value := "10" }]
  body := some ⟨#[72, 101, 108, 108, 111]⟩  -- "Hello" (5 bytes, not 10)
}
#eval decide (responseWithValidLength.contentLength = some 5)
#eval decide (responseWithValidLength.body.map (·.size) = some 5)
#eval decide (responseWithInvalidLength.contentLength = some 10)
#eval decide (responseWithInvalidLength.body.map (·.size) = some 5)

end ContractTests

-- Section 9: Proxy Tests
section ProxyTests

-- Test 9.1: Proxy validation
def validProxy : SWELib.Networking.Proxy.Proxy := {
  type := .forward
  host := "proxy.example.com"
  port := 8080
  auth := none
  allowedPorts := none
}
def invalidProxy : SWELib.Networking.Proxy.Proxy := {
  type := .forward
  host := ""
  port := 8080
}
#eval decide (SWELib.Networking.Proxy.Proxy.isValid validProxy)
#eval decide (SWELib.Networking.Proxy.Proxy.isValid invalidProxy)

-- Test 9.2: Port restrictions
def proxyWithPortRestrictions : SWELib.Networking.Proxy.Proxy := {
  type := .tunnel
  host := "proxy.example.com"
  port := 8080
  allowedPorts := some [80, 443, 8080]
}
#eval decide (SWELib.Networking.Proxy.Proxy.allowsPort proxyWithPortRestrictions 443)
#eval decide (SWELib.Networking.Proxy.Proxy.allowsPort proxyWithPortRestrictions 22)
#eval decide (SWELib.Networking.Proxy.Proxy.allowsPort validProxy 22)  -- No restrictions

-- Test 9.3: Via header addition
def proxyRequest : Request := {
  method := Method.GET
  target := RequestTarget.originForm "/" none
  headers := [{ name := FieldName.host, value := "example.com" }]
}
def proxiedRequest := SWELib.Networking.Proxy.addViaHeader proxyRequest Version.http11 "proxy.example.com"
#eval proxiedRequest.headers.get? ⟨"Via"⟩

-- Test 9.4: Proxy authentication
def proxyWithAuth : SWELib.Networking.Proxy.Proxy := {
  type := .forward
  host := "proxy.example.com"
  port := 8080
  auth := some { username := "user", password := "pass" }
}
#eval decide (SWELib.Networking.Proxy.Proxy.requiresAuth proxyWithAuth)
#eval decide (SWELib.Networking.Proxy.Proxy.requiresAuth validProxy)

end ProxyTests

-- Section 10: Content Coding Tests
section ContentCodingTests

-- Test 10.1: Content coding types
#eval repr (ContentCoding.gzip : ContentCoding)
#eval repr (ContentCoding.deflate : ContentCoding)
#eval repr (ContentCoding.compress : ContentCoding)
#eval repr (ContentCoding.identity : ContentCoding)
#eval repr (ContentCoding.other "br" : ContentCoding)

-- Test 10.2: Content coding equality
#eval decide ((ContentCoding.gzip : ContentCoding) = ContentCoding.gzip)
#eval decide ((ContentCoding.gzip : ContentCoding) = ContentCoding.deflate)

end ContentCodingTests

-- Summary function to count tests
def totalTestCount : Nat := 150  -- Approximate count

#eval s!"HTTP Conformance Test Suite - Total tests: {totalTestCount}"

end HttpConformanceTest